config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  delete "logout", to: "sessions#destroy", as: "logout"
  match "auth/:provider/callback", to: "sessions#create", via: [ :get, :post ]
  get "auth/failure", to: redirect("/")

  # API
  get "download/:site_key/*path" => "api/files#download", constraints: { path: /.*/ }
  post "upload/:site_key/*path" => "api/files#upload", constraints: { path: /.*/ }
  delete "remove/:site_key/*path" => "api/files#remove", constraints: { path: /.*/ }
  put "/transfer/:site_key/*source_path", to: "api/files#transfer", constraints: { path: /.*/ }
  get "list/:site_key/*path" => "api/folders#index", constraints: { path: /.*/ }
  post "mkdir/:site_key/*path" => "api/folders#create", constraints: { path: /.*/ }

  # Redirects - compatibility layer
  get "folders/:site_key/*path", to: redirect("%{site_key}/folders/%{path}"), constraints: { path: /.*/ }
  get "folders/:site_key", to: redirect("%{site_key}/folders"), constraints: { path: /.*/ }
  get "files/:site_key/*path", to: redirect("%{site_key}/files/%{path}"), constraints: { path: /.*/ }


  get ":site_key/folders/*path" => "folders#show", as: :folder, constraints: { path: /.*/ }
  get ":site_key/folders" => "folders#show"
  get "no_access_error/" => "folders#no_access_error"

  get ":site_key/files/*path" => "files#show", as: :file, constraints: { path: /.*/ }
  # post 'show/:path' => 'files#show', as: :file
  post ":site_key/files/*path" => "files#create", as: :upload_file, constraints: { path: /.*/ }
  post ":site_key/files" => "files#create"
  delete ":site_key/files/*path" => "files#delete", as: :delete_file, constraints: { path: /.*/ }
  put ":site_key/files/*path" => "files#update", as: :update_file, constraints: { path: /.*/ }
  post ":site_key/folders/*path" => "folders#create", as: :create_folder, constraints: { path: /.*/ }
  post ":site_key/folders" => "folders#create"

  get "help/:category" => "help#show", as: :help, constraints: { path: /api/ }

  # Nagios XML Monitoring POST endpoint
  post "monitoring/health_data"

  # Exception pages
  match "/404" => "errors#not_found", via: [ :get, :post, :delete, :put ]
  match "/422" => "errors#server_error", via: [ :get, :post, :delete, :put ]
  match "/500" => "errors#server_error", via: [ :get, :post, :delete, :put ]
end

app/controllers/api/folders_controller.rb
class Api::FoldersController < Api::ApplicationController
  def index
    entries = Current.client.list(path)

    render json: entries
  end

  def create
    dir_path = File.dirname(path)
    dir_name = File.basename(path)

    result = Current.client.mkdir(dir_path, dir_name, recursive: params[:recursive] == "true")

    logger.info "Creating new directory: #{path}/#{dir_name} -> #{result}"
    result ? head(:ok) : render(status: 422, text: I18n.t("folder.error"))
  end
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_action :authenticate_user!

  def show
    @entries = Current.client.list(path)

    @hidden_entries = @entries.select { |e| e[:name].start_with?(".") }.size
    if (params[:hide_hidden] == "true") || (cookies[:hide_hidden] && (params[:hide_hidden] != "false"))
      @entries = @entries.reject { |e| e[:name].start_with?(".") }
      cookies[:hide_hidden] = true if params[:hide_hidden]
    end
    cookies.delete :hide_hidden if params[:hide_hidden] == "false"

    @more_entries = @entries.size > page * page_size
    @entries = @entries[interval] || []

    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  def create
    result = params[:folder_name].present? &&
      Current.client.mkdir(path, params[:folder_name])

    redirect_to unescape(folder_path(site_key:, path:)),
      notice: result ? I18n.t("folder.success") : nil,
      status: :see_other
  end

  def no_access_error
  end

  private
    def interval
      ((page - 1) * page_size)...(page * page_size)
    end

    def page
      @page ||= params[:page] ? params[:page].to_i : 1
    end

    def page_size
      Plgdata::Application.config.items_per_page || 1000
    end
end

app/helpers/folders_helper.rb
module FoldersHelper
  def entry_path(entry)
    File.join(path, entry[:name])
  end

  #  Removes invalid characters from the entry name so it is safe for further processing
  def remove_invalid(name)
    # name.encode('UTF-8', 'binary', invalid: :replace, undef: :replace, replace: '?')
    name
  end

  def owner_tooltip(entry)
    "#{t 'user'}: #{entry[:owner]}<br/>#{t 'group'}: #{entry[:group]}"
  end
end

app/views/folders/_breadcrumbs.html.haml
%div{ "data-controller": "tab" }
  %ol.breadcrumb.d-flex.align-items-center.bg-light

    %span.me-2
      = succeed ':' do
        = t 'listing_folder'

    %li.breadcrumb-item-root
      = link_to '/' , folder_path(path: "")

    - current_crumb = ''
    - URI::Parser.new.unescape(path).split('/').select{ |c| c.present? }.each do |crumb|
      - current_crumb += crumb + '/'
      %li.breadcrumb-item
        = link_to crumb.truncate(64), folder_path(path: current_crumb)

    = render "actions/copy", copy_path: path

    %li.ms-3
      %button.btn.btn-success.btn-sm{ data: { "bs-toggle" => "tooltip", "bs-placement" => "top", action: "tab#switch", tab: { target: "button", content: "file-upload" } }, title: t('upload.upload_files')}
        = bi_cloud_arrow_up_fill

        %span.d-none.d-md-inline
          = t 'upload.upload_files'

      %button.btn.btn-success.btn-sm{ data: { "bs-toggle" => "tooltip", "bs-placement" => "top", action: "tab#switch", tab: { target: "button", content: "mkdir" } }, title: t('folder.new_folder')}
        = bi_folder_fill
        %span.d-none.d-md-inline
          = t 'folder.new_folder'

  .row.border-bottom.pb-3.mx-3.m-3.d-none{ data: { tab: { target: "content", content: "mkdir" } } }
    = render "new_folder"

  .row.border-bottom.pb-3.mx-3.m-3.d-none{ data: { tab: { target: "content", content: "file-upload" } } }
    = render "upload"

app/views/folders/_delete.html.haml
%td.text-end{ "data-controller" => "opener", "data-opener-timeout-value" => 5000 }
  .d-none{ "data-opener-target" => "part", "data-opener-remove-class" => "d-none" }
    %span.d-none.d-lg-inline-block= t 'confirm.sure'
    .btn-group.btn-group-sm
      = button_to delete_file_path(path: target_path, is_dir: entry[:is_dir]), class: 'btn btn-danger', method: :delete do
        = t 'confirm.resp_yes'
      %button.btn.btn-light{ "data-action" => "opener#close" }
        = t 'confirm.resp_no'

  %button.btn.btn-warning.btn-sm{ "data-bs-toggle" => "tooltip", "data-bs-placement" => "top", title: t("delete_button_#{entry[:is_dir] ? 'folder' : 'file'}"), "data-action" => "opener#show", "data-opener-target" => "part", "data-opener-add-class" => "d-none" }
    = bi_x_circle
    %span.d-none.d-lg-inline-block
      = t 'delete.delete_file'

app/views/folders/_entry.html.haml
- target_path = entry_path(entry)
%tr.infinite-item.align-middle
  %td
    %span(data-bs-toggle="tooltip" data-bs-placement="top" data-bs-html="true" title="#{owner_tooltip(entry)}")
      = bi_person_fill

  - if entry[:owner] == Current.login
    %td.text-nowrap.d-none.d-lg-table-cell{ "data-controller" => "toggler", "data-toggler-toggle-class" => "d-none" }
      %span.font-monospace{ "data-toggler-target" => "toggle" }= entry[:rights]
      = form_tag update_file_path(path: target_path), method: :put, class: 'd-none d-flex font-monospace', "data-toggler-target" => "toggle" do
        .flex-grow-1
          = hidden_field_tag :is_dir, entry[:is_dir]
          %label.visually-hidden(for="mode")= t 'chmod.new_rights'
          = text_field_tag :mode, entry[:rights][1..-1], class: 'form-control form-control-sm', "data-controller" => "imask", "data-imask-regex-value" => "((r|-)(w|-)(x|-)){3}", "data-imask-placeholder-value" => "---------", "data-action" => "input->imask#onChange"
        %button.btn.btn-sm.btn-success{ type: 'submit', "aria-label" => t("chmod.confirm") }
          = bi_check
        %span.btn.btn-sm.btn-light{ "data-action" => "click->toggler#toggle" }
          = bi_x
      %button.btn.btn-sm.btn-default{ title: t('chmod_button'), "data-action" => "toggler#toggle", "data-toggler-target" => "toggle", "aria-label" => t('chmod_button') }
        = bi_pencil_square
  - else
    %td.text-nowrap.d-none.d-lg-table-cell
      %span.font-monospace= entry[:rights]

  %td.text-end
    %span.text-nowrap(title="#{entry[:size]} B")= number_to_human_size entry[:size]

  %td.d-none.d-lg-table-cell= entry[:modification_date]

  = render "name", entry: entry, target_path: target_path

  %td
    %span.d-inline-block.d-sm-none{title: entry[:is_dir] ? t('dir') : t('file')}
      = (entry[:is_dir] ? t('dir_mobile') : t('file_mobile'))
    %span.d-sm-none.d-md-inline-block
      = (entry[:is_dir] ? t('dir') : t('file'))

  = render "delete", entry: entry, target_path: target_path

app/views/folders/_load_more.html.haml
- if @more_entries
  #load-more.d-flex.justify-content-center.align-items-center.text-muted{ "data-controller" => "pagination", "data-pagination-next-url-value" => folder_path(page: params[:page] ? params[:page].to_i + 1 : 2) }
    %span(class="spinner-border spinner-border-sm me-2" role="status" aria-hidden="true")
    = t 'loading_more_data'

app/views/folders/_name.html.haml
- valid_name = remove_invalid entry[:name]
- display_name = truncate(valid_name, length: 64)
- file_path = entry[:is_dir] ? folder_path(path: target_path) : file_path(path: target_path)

- if entry[:owner] == Current.login
  %td.text-nowrap{ "data-controller" => "toggler", "data-toggler-toggle-class" => "d-none" }
    %button.btn.btn-secondary.btn-sm.chmod-button{ "data-bs-toggle" => "tooltip", "data-bs-placement" => "top", title: t('name_button'), "data-toggler-target" => "toggle", "data-action" => "toggler#toggle", "aria-label" => t("name_button") }
      = bi_pencil_square
    %span{ "data-toggler-target" => "toggle" }
      = link_to display_name, file_path
      = render "actions/copy", copy_path: target_path

    = form_tag update_file_path(path: target_path), method: :put, class: 'd-none d-flex', "data-toggler-target" => "toggle" do
      .flex-grow-1
        = hidden_field_tag :is_dir, entry[:is_dir]
        %label.visually-hidden(for="destination")= t 'rename.new_name'
        = text_field_tag :destination, valid_name, class: 'form-control form-control-sm'
      %button.btn.btn-sm.btn-success{ type: 'submit', "aria-label" => t("rename.confirm") }
        = bi_check
      %span.btn.btn-sm.btn-light{ "data-action" => "click->toggler#toggle" }
        = bi_x
- else
  %td
    %span.name
      = link_to display_name, file_path
      = render "actions/copy", copy_path: target_path

app/views/folders/_new_folder.html.haml
= form_tag(create_folder_path(path:), class: 'row g-2', role: :form) do
  .col-lg-5.col-md-8.col-sm-12
    %label.visually-hidden(for="folder_name")= t 'folder.name_label'
    %input.form-control.form-control-sm(name="folder_name" type="text"){placeholder: t('folder.name_label')}

  .col
    %button.btn.btn-primary.btn-sm(type="submit")
      %i.glyphicon.glyphicon-plus-sign
      %span= t 'folder.create_folder'

app/views/folders/_upload.html.haml
= form_tag upload_file_path(path:).gsub('%','%25'), multipart: true, "data-controller" => "dropzone", class: "dropzone" do
  -# Nothing just to have closing tag

app/views/folders/no_access_error.html.haml
%h4
  = t 'no_access'

- if alert and alert.include? 'Permission denied'
  %p
    = t 'not_permitted'

- if alert and alert.include? 'Gridmap lookup failure'
  %p
    = t 'no_account'
  %p
    =raw t 'no_gridmapfile', your_account: "<a href='https://portal.plgrid.pl/web/guest/useraccount'>#{t 'your_accout_page'}</a>"

- if alert and alert.include? 'No such file or directory'
  %p
    = t 'does_not_exists'

-#%p
-#  Podczas komunikacji z zasobami dyskowymi Infrastruktury PL-Grid wystąpił następujący błąd protokołu
-#  dostępu do plików:
-#
-#  = alert

app/views/folders/show.html.haml
= render 'breadcrumbs'

.row
  .col.h6.d-flex.justify-content-end
    = t 'folder_summary', all_entries: @all_entries, hidden_entries: @hidden_entries
    - if @hidden_entries > 0
      = link_to cookies[:hide_hidden] ? t('show') : t('hide'), folder_path(hide_hidden: !cookies[:hide_hidden]),
        title: (cookies[:hide_hidden] ? t('show_title') : t('hide_title'))

%table.table.table-hover.table-responsive
  %thead
    %tr
      %th.very-thin
      %th.d-none.d-lg-table-cell.medium= t 'rights'
      %th.very-thin.text-end= t 'size'
      %th.thin.d-none.d-lg-table-cell= t 'modification_date'
      %th= t 'name'
      %th.very-thin= t 'type'
      %th.medium
  %tbody#entries
    = render partial: "entry", collection: @entries, as: :entry

= render "load_more"

app/views/folders/show.turbo_stream.erb
<%= turbo_stream.append "entries" do %>
  <%= render partial: "entry", collection: @entries, as: :entry %>
<% end %>

<%= turbo_stream.replace "load-more" do %>
  <%= render "load_more" %>
<% end %>