config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  delete "logout", to: "sessions#destroy", as: "logout"
  match "auth/:provider/callback", to: "sessions#create", via: [ :get, :post ]
  get "auth/failure", to: redirect("/")

  # API
  get "download/:site_key/*path" => "api/files#download", constraints: { path: /.*/ }
  post "upload/:site_key/*path" => "api/files#upload", constraints: { path: /.*/ }
  delete "remove/:site_key/*path" => "api/files#remove", constraints: { path: /.*/ }
  put "/transfer/:site_key/*source_path", to: "api/files#transfer", constraints: { path: /.*/ }
  get "list/:site_key/*path" => "api/folders#index", constraints: { path: /.*/ }
  post "mkdir/:site_key/*path" => "api/folders#create", constraints: { path: /.*/ }

  # Redirects - compatibility layer
  get "folders/:site_key/*path", to: redirect("%{site_key}/folders/%{path}"), constraints: { path: /.*/ }
  get "folders/:site_key", to: redirect("%{site_key}/folders"), constraints: { path: /.*/ }
  get "files/:site_key/*path", to: redirect("%{site_key}/files/%{path}"), constraints: { path: /.*/ }


  get ":site_key/folders/*path" => "folders#show", as: :folder, constraints: { path: /.*/ }
  get ":site_key/folders" => "folders#show"
  get "no_access_error/" => "folders#no_access_error"

  get ":site_key/files/*path" => "files#show", as: :file, constraints: { path: /.*/ }
  # post 'show/:path' => 'files#show', as: :file
  post ":site_key/files/*path" => "files#create", as: :upload_file, constraints: { path: /.*/ }
  post ":site_key/files" => "files#create"
  delete ":site_key/files/*path" => "files#delete", as: :delete_file, constraints: { path: /.*/ }
  put ":site_key/files/*path" => "files#update", as: :update_file, constraints: { path: /.*/ }
  post ":site_key/folders/*path" => "folders#create", as: :create_folder, constraints: { path: /.*/ }
  post ":site_key/folders" => "folders#create"

  get "help/:category" => "help#show", as: :help, constraints: { path: /api/ }

  # Nagios XML Monitoring POST endpoint
  post "monitoring/health_data"

  # Exception pages
  match "/404" => "errors#not_found", via: [ :get, :post, :delete, :put ]
  match "/422" => "errors#server_error", via: [ :get, :post, :delete, :put ]
  match "/500" => "errors#server_error", via: [ :get, :post, :delete, :put ]
end

app/views/layouts/_footer.html.haml
.container.d-flex.justify-content-between.align-items-center
  %span.text-muted
    Copyright &copy; 2013-2021
    = link_to t(:author), footer_link('cyfronet')
    = t :reserved
    = link_to t(:helpdesk), footer_link('helpdesk')
    = t :cookies_info
    = succeed ':' do
      = t :further_resources
    = succeed '.' do
      = link_to t('api_link'), help_path(category: :api)

  %span.text-muted
    = link_to image_tag('cyfronet_logo.png'), footer_link('cyfronet')
    = link_to image_tag('logo_plus.png'), footer_link('plgrid')
    = image_tag("poig_logo_#{I18n.locale or 'pl'}.png")

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-primary(role="navigation")
  .container-fluid
    = link_to "PLG-Data", root_path, class: "navbar-brand"

    %button.navbar-toggler(type="button" data-bs-toggle="collapse" data-bs-target="#full-navbar" aria-controls="full-navbar" aria-expanded="false" aria-label="Toggle navigation")
      %span.navbar-toggler-icon

    .navbar-collapse.collapse#full-navbar
      %ul.navbar-nav.me-auto

        - if Current.user.present?
          - Current.user.site_clients.each do |site_client|
            %li.nav-item.dropdown
              %a.nav-link.dropdown-toggle(href="#" data-bs-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false")
                = site_client.name
                %b.caret
              .dropdown-menu
                - site_client.dirs.each do |name, path|
                  = link_to name, folder_path(site_key: site_client.key, path: path.delete_prefix("/")),
                    class: 'dropdown-item'
        - else
          .navbar-text= t 'leadline'

      %ul.navbar-nav.justify-content-end
        - if Current.user.present?
          - if content_for?(:help)
            %li{title: t('main_menu.help.tooltip'), data: {placement: 'bottom'}}
              %a.navbar-btn(href='#' data-toggle='collapse' data-target='.help-content')
                %i.icon-question-sign.icon-white

          -#%li{:title => t('main_menu.issue.tooltip'), 'data-placement' => 'bottom'}
          -#  %a(data-target='#report-issue' data-toggle='modal' href='#')
          -#    %i.icon-wrench.icon-white
          -#

          %li.nav-item
            = button_to logout_path, method: :delete, class: "nav-link btn btn-link" do
              = bi_eject_fill
              = t 'sign_out'
          %li.nav-item
            %button.nav-link.btn.btn-link{ "data-bs-toggle" => "tooltip", "data-bs-placement" => "bottom", "data-bs-html" => "true", title: user_info(Current.user) }
              = bi_person_fill

      %ul.navbar-nav.justify-content-end
        %li.nav-item
          .btn-group(data-toggle="buttons-radio")
            - I18n.available_locales.each do |lang|
              - opts = params
              - opts[:locale] = lang
              = link_to_unless(I18n.locale == lang, lang.upcase, opts.permit!, class: 'navbar-btn btn btn-sm btn-primary') do
                .navbar-btn.btn.btn-sm.btn-primary.active= lang.upcase

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Plgdata</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="d-flex flex-column h-100 pb-0">
    <main class="container flex-shrink-0">
      <%= render 'layouts/navbar' %>

      <% if notice %>
          <p class="alert alert-dismissable alert-success flash-notice mt-3"><%= notice %></p>
      <% end %>
      <% if alert %>
          <p class="alert alert-dismissable alert-danger mt-3"><%= alert %></p>
      <% end %>

      <div class="bg-ultra-light mt-3 p-3 border border-2">
        <%= yield %>
      </div>
    </main>

    <footer class="footer mt-auto py-3">
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</body>
</html>